### ISSUE TITLE
duplicate instances in the negative set

### ISSUE THREAD

**Issue by albarron** [taolei87/askubuntu#1]
Dear @taolei87 , first of all, thank you for compiling this interesting corpus.

While exploring it, I have noted that the negative instances in the train_random.txt set include duplicates sometimes. For instance:

query : negative (random) instances appearing more than once
163842 : 217493, 185573
393230 : 197044
...

This phenomenon occurs in 1136 out of 12,723 instances. I fully understand this issue is not crucial and fixing it would change nothing, as it simply implies that a negative instance is considered twice. Still you might want to check the random instances selector in case there are other issues or side effects.

Best regards
albarron

**Comment by taolei87** [comment]
Hi albarron,

Thanks a lot for pointing this out. I believe my coauthor who generates this file simply used a generator to sample questions from the corpus (with replacement). 

I'm quite busy with a deadline right now, but I will check it again and remove duplicate negaitves if necessary.

Best,
Tao
