### ISSUE TITLE
Number of Tokens in vectors_pruned.200.txt

### ISSUE THREAD

**Issue by tarun0505** [taolei87/askubuntu#2]
The number of tokens in the file vectors_pruned.200.txt is 100406.
I wanted to know if some of the tokens from the askUbuntu Dataset have been removed to achieve the above number of 100406.
If not which tokenizer is used over the data.

**Comment by taolei87** [comment]
Hi tarun0505,
~~I used NLTK default tokenizer, then trained word2vec to obtain embeddings.~~ 

*\* This is not exactly true. I was confused by another project I've worked on. sry. See below my follow-up comment.

I guess word2vec by default remove low-frequent tokens.

**Comment by taolei87** [comment]
@tarun0505 let me try to find the original pre-processing scripts.

**Comment by taolei87** [comment]
@tarun0505 okay, now i remember the whole preprocessing now. the second co-author Rish (Hrishikesh) helped trained the word embeddings. As described in our paper, he used all available website text in Stack Exchanged domain, plus wikipedia. 

This results in a file with 954K word vectors. Not all the words appear in the askubuntu corpus, so to reduce the file size, I pruned word embeddings.

Do you have any problem using the dataset?
If you want the whole pre-trained word embeddings, I can upload that file (619M).
Unfortunately I'm not quite sure what tokenizer was used by Rish (I assume it's a popular library such as NLTK), if you want the raw corpus for training the embedding, I can contact Rish.

**Comment by tarun0505** [comment]
@taolei87 Thanks for the reply.
Please Upload whole pre-trained word embeddings if you can.
That would be very helpful.
The exact problem I had was that when I used NLTK to tokenize the AskUbuntu dataset, I got 620k unique tokens, whereas the number of tokens for which vectors are provided are only 100406 tokens.

**Comment by taolei87** [comment]
@tarun0505 Sure. 
Let me upload the embeddings to Google Drive (maybe). I'll try to find the tokenized corpus that is used to train the embeddings as well, in case you wanna re-run word2vec.
I'm doing an internship and will do this at night. Plz be patient :)

**Comment by taolei87** [comment]
@tarun0505  I uploaded the word embeddings and raw corpora on Google Drive.
https://drive.google.com/folderview?id=0B-btHzfJjPnobXZ0MndjSkxkRkk#list

README also updated.

**Comment by tarun0505** [comment]
@taolei87 Thank You.

**Comment by CairneRain** [comment]
@taolei87 The google drive link now requires access to visit. 
Would you like to open the access to me?
It will be helpful to me. 
Thank you!

Rui Chen
chen107101@gmail.com
